// This file is generated by Flutter and should be configured with your Firebase project
// Run: `flutterfire configure` to auto-generate this file with your Firebase settings

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjHH2_G5ukmaZmpqtOdDYrrdI_R5VxhFM',
    appId: '1:755102328642:web:a5c3515207152289d48adb',
    messagingSenderId: '755102328642',
    projectId: 'kristianonochie-ea18d',
    authDomain: 'kristianonochie-ea18d.firebaseapp.com',
    storageBucket: 'kristianonochie-ea18d.firebasestorage.app',
    measurementId: 'G-ZW7ZL980CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbGS1Wb7ZjAwKVdABz13kaJ5JUblSowCo',
    appId: '1:755102328642:android:e904d7f604b21916d48adb',
    messagingSenderId: '755102328642',
    projectId: 'kristianonochie-ea18d',
    storageBucket: 'kristianonochie-ea18d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpvhWPjvE7-RYOTOZVCS0fuojkL_VeCvg',
    appId: '1:755102328642:ios:3ee913de3da43742d48adb',
    messagingSenderId: '755102328642',
    projectId: 'kristianonochie-ea18d',
    storageBucket: 'kristianonochie-ea18d.firebasestorage.app',
    iosBundleId: 'com.newlifechurch.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpvhWPjvE7-RYOTOZVCS0fuojkL_VeCvg',
    appId: '1:755102328642:ios:3ee913de3da43742d48adb',
    messagingSenderId: '755102328642',
    projectId: 'kristianonochie-ea18d',
    storageBucket: 'kristianonochie-ea18d.firebasestorage.app',
    iosBundleId: 'com.newlifechurch.app',
  );
}
